### ISSUE TITLE
请问下，我编译ex8_6.cpp报错，代码拷贝跟您一样的也报错

### ISSUE THREAD

**Issue by likui911** [pezy/CppPrimer#102]
d:/Source/CppPrimer/chapter08/ex8_6.cpp:15: undefined reference to `read(std::istream&, Sales_data&)'
d:/Source/CppPrimer/chapter08/ex8_6.cpp:17: undefined reference to `read(std::istream&, Sales_data&)'
d:/Source/CppPrimer/chapter08/ex8_6.cpp:19: undefined reference to `Sales_data::combine(Sales_data const&)'
d:/Source/CppPrimer/chapter08/ex8_6.cpp:21: undefined reference to `print(std::ostream&, Sales_data const&)'
d:/Source/CppPrimer/chapter08/ex8_6.cpp:25: undefined reference to `print(std::ostream&, Sales_data const&)'

**Comment by pezy** [comment]
你有这句吗？

#include "../ch07/ex7_26.h"

路径文件可都对？

**Comment by likui911** [comment]
这句是对的，我的路径不一样
