### ISSUE TITLE
在练习10.3.3节，练习10.21

### ISSUE THREAD

**Issue by aLazyGreenhand** [pezy/CppPrimer#103]
不管是中文题：编写一个lambda，捕获一个局部int变量并递减变量值，**直至**它变为0
还是英文原文：Write a lambda that captures a local int variable and decrements that variable **until it reaches 0**.
怀疑对题意的理解可能出错

	int local_val = 7;
	auto decrement_to_zero = [&local_val](){
		if (local_val == 0)
			return true; 
		while (local_val > 0)
			--local_val;
		return false; 
	};

	cout << decrement_to_zero() << endl;

**Comment by pezy** [comment]
> 怀疑对题意的理解可能出错

没太明白您的意思, 怎么出错了?

**Comment by pezy** [comment]
如果局部变量是负数, 您这个 lambda 就不会递减该变量值了. 是否违反了题意呢?

**Comment by aLazyGreenhand** [comment]
确实也有，那按这么说感觉也是没法无懈可击啊
