### ISSUE TITLE
ex6_23

### ISSUE THREAD

**Issue by newgood1** [pezy/CppPrimer#105]
` print(j) ` 编译不通过，存在二义性?
```
void print(const int *pi);
void print(int (&arr)[2]);
int j[2]={0,1};
print(j);
```

**Comment by pezy** [comment]
请问你用的什么编译器?

这个不存在二义性, 因为`int (&arr)[2]` 显然更符合一些.

这是在线编译的结果: http://coliru.stacked-crooked.com/a/6feb48193a611e88

**Comment by newgood1** [comment]
用vs2015编译会出现错误
more than one instance of overloaded function "print" matches the argument list
用g++编译是可以通过的
