### ISSUE TITLE
ex10_09的代码中的auto const怎么理解？

### ISSUE THREAD

**Issue by why2cs** [pezy/CppPrimer#117]
代码第19行：
`    for (auto const& elem : seq) std::cout << elem << " ";`
第一眼看到auto const的时候突然有点恍惚，不是应该是const auto么，随后翻书看了一下例子，都用的是const auto。但是此处的auto const编译也没错。

不太清楚auto const该怎么理解？应该不是顶层const和底层const这样的理解吧？
用如下代码测试了一下：

	const int consti = 5;		
	int i = 5;	//int				
	auto i2 = consti;  //int
	const auto i3 = consti;		
	const auto i4 = i;			
	auto const i5 = consti;		
	auto const i6 = i;			

除了加注释的部分是int类型，其他均为const int。
是不是可以理解为const auto 和auto const没有区别？只是习惯问题？

**Comment by wtlusvm** [comment]
[C++: copy from stackoverflow](https://stackoverflow.com/questions/10709897/is-auto-const-and-const-auto-the-same)

**Comment by why2cs** [comment]
@wtlusvm thanks！
