### ISSUE TITLE
ex 7-35

### ISSUE THREAD

**Issue by FunBing** [pezy/CppPrimer#119]
根据7.4.1节中“类型名要特殊处理”部分的解释，类型名是不是不应该在类中重新定义？也就是说在类中第二次
```c++
typedef double Type;
```
本身就是错的。

**Comment by wtlusvm** [comment]
>However, in a class, if a member uses a name from an outer scope and that name is a type, then the class may not subsequently redefine that name.

注意到，前提条件是有一个成员使用了那个类型别名，然后在类的剩余代码又重定义了那个类型别名，才是错误的。按照书上的例子，就是：

```cpp
typedef double Money;
class Account {
public:
  Money balance() { return bal; }

private:
  typedef double Money;
  Money bal;
};
```

是错误的，因为先定义了成员函数`Account.balance`使用了类型别名Money。如果调换下顺序，变成下面这样，就没错：

```cpp
typedef double Money;
class Account {
public:
  typedef int Money;
  Money balance() { return bal; }

private:
  Money bal;
};
```

**Comment by FunBing** [comment]
Soga，是我看书不仔细了。
