### ISSUE TITLE
ex11.31

### ISSUE THREAD

**Issue by why2cs** [pezy/CppPrimer#121]
练习11.31的题干要求是：在multimap中查找一个元素并删除它。
给出的代码为：
```
    auto found = authors.find(author);
    auto count = authors.count(author);
    while (count) {
        if (found->second == work) {
            authors.erase(found);
            break;
        }
        ++found;
        --count;
    }
```
考虑到multimap允许存在这种情况：
`m = { {"a","1"}, {"a","2"},{"a","1"},{"a","2"} };`
此处代码改为下面的是不是更好？
```
	for (auto it = authors.find(author); (it != authors.end()) && (it->first == author); )
	{
		if (it->second == work)
			it = m.erase(it);
		else
			++it;
	}
```

**Comment by wtlusvm** [comment]
考虑以下情况：

`multimap m = { {"b","1"}, {"a","2"},{"a","2"},{"a","2"},{"a","2"},{"a","2"},{"a","2"},{"b","1"} };`

使用你给出的`for`循环语句：
```cpp
for (auto it = m.find(author); (it != m.end()) && (it->first == author); ) //假定string author("a");
{
	if (it->second == work)//假定unsigned int work = 1;
		it = m.erase(it);
	else
		++it;
}
```

在删除第一个`{"b","1"}`后，`it`指向第一个`{"a","2"}`，不满足`for`循环条件语句，退出循环。而最后一个元素，即还有一个`{"b","1"}`没有被删除。

**Comment by why2cs** [comment]
@wtlusvm  multimap是ordered container，会按照key的大小进行存储。用下列代码初始化：
`multimap m = { {"b","1"}, {"a","2"},{"a","2"},{"b","1"} };`
得到的结果也是
`{{"a","2"},{"a","2"},{"b","1"},{"b","1"}}`

**Comment by wtlusvm** [comment]
震惊，我怕是记错了
