### ISSUE TITLE
p201 const string &shorterString(const string &s1,const string &s2

### ISSUE THREAD

**Issue by TolicWang** [pezy/CppPrimer#122]
#include<iostream>
using namespace std;
const string &shorterString(const string &s1,const string &s2)
{
    return s1.size() <= s2.size() ? s1 : s2;
}
int main()
{
    string s1 = "hello",s2 = "girl",s3;
    s3 = shorterString(s1,s2); //此时返回的是s2的引用，即此后s3也将是ｓ２的别名，对吗？ 
    s3 += 's'; // 但是为什么，执行完这句之后，变量ｓ２的值依旧是girl
    cout<<s2<<"    "<<s3<<endl;
    return 0;
}

**Comment by pezy** [comment]
> 即此后s3也将是ｓ２的别名，对吗？

不对，s3 怎么成引用了。。。

**Comment by TolicWang** [comment]
return s1.size() <= s2.size() ? s1 : s2;   那这条语句到底返回的是什么？ 返回的是谁的引用？

**Comment by pezy** [comment]
> 那这条语句到底返回的是什么？ 返回的是谁的引用

返回的不是 s1 就是 s2 啊。这里返回的当然是 const 引用。但你得看返回值赋给谁。s3 的定义是：`string`，不能因为给它赋一个引用，它自己就变身引用了吧？

**Comment by TolicWang** [comment]
既然函数的返回类型已经声明是引用型了，为什么ｓ３与返回值类型不一样？ 或者说应该怎么定义一个变量来接收这个返回值？

**Comment by pezy** [comment]
> 为什么ｓ３与返回值类型不一样？

s3 是你定义的类型: `string`, 返回值的类型：`const string&`，当然不一样。

> 应该怎么定义一个变量来接收这个const string& 类型的返回值？

```cpp
const string& s4 = shorterString(s1,s2);
```

**Comment by TolicWang** [comment]
明白了。 多谢指教！
