### ISSUE TITLE
练习7.10

### ISSUE THREAD

**Issue by TolicWang** [pezy/CppPrimer#127]
在下面if语句中，条件部分的作用是什么？
if ( read ( read ( cin, data1), data2) )

istream &read(istream& is, Sales_data &item)
{
    double price = 0;
    is>>item.bookNo>>item.units_sold>>price;
    item.revenue = price * item.units_sold;
    return is;
}

**Comment by pezy** [comment]
> 条件部分的作用是什么？

是问 read 函数的作用？那很明白啊，将输入流的信息提取到 Sales_data 对象中。if 语句里无非是嵌套调用了 read 两次而已。

另外，用 if 直接判断流，是在检查流里是否出现错误。详见：http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool

**Comment by TolicWang** [comment]
> 将输入流的信息提取到 Sales_data 对象中
如果是这样的话，那在执行read ( read ( cin, data1), data2); 时，输入一次值之后，data1,data2就都应该被成功写入了，且两个对象成员的值都是一样的。 因为先执行read ( cin, data1)时，将输入流中的信息提取到data1中，然后read()又返回这个流给最外层的read所以此时对象data2也被成功写入了。  
可是，为什么在运行的时候，还是要分别两个输入data1和data2的数据？ 不知道你有没有听懂我的描述

**Comment by pezy** [comment]
> 然后read()又返回这个流给最外层的read所以此时对象data2也被成功写入了

属于 data1 那一组数据已经被第一次调用 read 时读取了。再次进入 read 时，这个流里，已经不包含 data1 的数据了，如果你没有输入 data2 的数据，那么 data2 是无法写成功的（可能是空）。

**Comment by TolicWang** [comment]
懂了。 多谢！
