### ISSUE TITLE
ex16.21.22

### ISSUE THREAD

**Issue by Felon03** [pezy/CppPrimer#132]
在Ex16.21.22的[wy_queryresult.cpp](https://github.com/pezy/CppPrimer/blob/master/ch16/ex16.21.22/wy_queryresult.cpp)中

``` c++
inline wy_queryResult::wy_queryResult(const wy_queryResult &qr):
    counter(qr.getCounter()), queryWord(qr.getQueryWord()),
    sp_file(qr.getSp_file()), sp_Qmap(qr.getSp_Qmap())
{
}
```
报错，错误提示为"无法解析的外部命令"(环境是VS 2015)，去掉inline就通过了。
我在书上看到inline应该定义在头文件中，这里的inline是不是多余的？

**Comment by pezy** [comment]
是多余的。
