### ISSUE TITLE
About exercise 14.43

### ISSUE THREAD

**Issue by Xiangwk** [pezy/CppPrimer#133]
# Exercise information

Exercise 14.43

# Question

Is this exercise should use all_of instead of any_of ?

# Your enviroment information

- **System**: Win10
- **Compiler version/IDE**: VS2017

**Comment by Xiangwk** [comment]
Ah，I know that, is a translation problem!

**Comment by pezy** [comment]
@Xiangwk Yes, you get the point. check Mooophy/Cpp-Primer#251
