### ISSUE TITLE
Question of exercise 7.43.

### ISSUE THREAD

**Issue by Roller44** [pezy/CppPrimer#134]
### Exercise information

Exercise 7.43

### Question or Bug

Question: why can't use "C() = default;"?

### Your enviroment information

- **System**:  :grey_question: Ubuntu 16.04 LTS
- **Compiler version/IDE**:  :grey_question: g++ 5.4.0

**Comment by amirags** [comment]
If I understand correctly, your intention is define the default ctor.  The way to do that in C++ is to assign the members its default explicitly (as there is no "default" keyword to do so).  In the exercise, same is done by def(0) where def is a private member of type NoDefault.

**Comment by Roller44** [comment]
I believe that the keyword "default" is feasible (you can refer [exercise 7.32](https://github.com/pezy/CppPrimer/blob/master/ch07/ex7_32.h)). I have being thinking a while and maybe the reason it cannot be use in this exercise is that the memeber def is a member of type NoDefault, which is an artifitial type and cannot be initialized by synthesized default constructor.

**Comment by amirags** [comment]
I stand corrected, default has been introduced with C++11 while my comment was based on C++98.  Having said that, I see the point of default not working for def which is of type NoDefault, hence making it not obvious to implement for the compiler.

**Comment by Roller44** [comment]
Thanks, man.
