### ISSUE TITLE
About exercise 16.41

### ISSUE THREAD

**Issue by Xiangwk** [pezy/CppPrimer#135]
### Question

I think the answer is wrong, because decltype(expression) is the expression's return type, if I use the sum like sum(INT_MAX, INT_MAX), it will print -2 bacause there are two int value do addition and the return type is also int.

But I cannot come up with an idea....

- **System**:  Windows10
- **Compiler version/IDE**:  VisualStudio2013

**Comment by pezy** [comment]
IMHO, because we cannot know the type of the `sum`'s arguments, using a promotion trait class is the only way to protect against overflowing at the compile time.

In your question, we can solve it by this way:

```cpp
#include <iostream>

template<typename T>
struct promote;

template<>
struct promote<int> // promote int to long long int
{
	using type = long long int;
};

template<typename T>
using promote_t = typename promote<T>::type;

template <typename T> auto sum(T lhs, T rhs) -> promote_t<T>
{
	return static_cast<promote_t<T>>(lhs) + rhs;
}

int main()
{
	auto s = sum(INT_MAX, INT_MAX);
	std::cout << s << std::endl; // output: 4294967294
}
```

**Comment by Xiangwk** [comment]
Brilliant! I think it is a good idea, thx! 
But I think this problem is hard to solve perfectly with just a template function.
But it is just an exercise, haha~Thank you for responding!

**Comment by pezy** [comment]
More better answers are always welcome. 😋
