### ISSUE TITLE
ex16.38

### ISSUE THREAD

**Issue by oven-yang** [pezy/CppPrimer#137]
### Exercise 16.38:
When we call make_shared (§ 12.1.1, p. 451), we have to provide an
explicit template argument. Explain why that argument is needed and
how it is used.

### Question or Bug
I think the answer is wrong. Look the following code
```
template<typename T> void * fun(T x)
{
    T* p = new T(x) ; 
    return p ; 
}
fun(11) ;
fun(string("123")) ;
```
fun(T) can be called without explicit template argument.

From [cppreference](http://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared), the make_shared is decalred as
```
template< class T, class... Args >
shared_ptr<T> make_shared( Args&&... args );
```
So I think the answer should be compiler couldn't deduce template parameter "T" from the parameter  provided. As a result of failed deduction, make_shared has no possibility to to determine how big the size it should allocate, but compile process has been interrupted before that.

**Comment by pezy** [comment]
Fixed by https://github.com/pezy/CppPrimer/commit/062d4c54545280b5313ec8f83d3ed9bec7c4502b#diff-062f693961b4160c20cff7761aaf2865R344
