### ISSUE TITLE
Exercise 4.37 : the usage of reinterpret_cast

### ISSUE THREAD

**Issue by mengDTT** [pezy/CppPrimer#144]
### Exercise information

> Exercise 4.37
> Rewrite each of the following old-style casts to use a named cast:
```c++
char *pc;
void *pv;
pc = (char*) pv;
```
### Question or Bug

In your answer, you used `pc = reinterret_cast<char*> pv` to make a replacement, there is a small question, **why not** use `static_cast` instead?

**Comment by pezy** [comment]
> why not use `static_cast` instead

For casting to and from `void*`, `static_cast` should be preferred. But it should be a certain type from begin to end. In this case, `pv` point to a `double`, then `pc` force to cast to `char*`. It is a completely different type, so `reinterpret_cast` should be preferred here.

check <https://en.cppreference.com/w/cpp/language/reinterpret_cast> example codes for more references.
