### ISSUE TITLE
Exercise 2.35 auto变量会去掉顶层const

### ISSUE THREAD

**Issue by PoacherBro** [pezy/CppPrimer#148]
### Exercise information

习题2.35，题目为：
> Determine the types deduced in each of the following definitions. Once you’ve figured out the types, write a program to see whether you were correct.

> ```cpp
> const int i = 42;
> auto j = i;
> const auto &k = i;
> auto *p = &i;
> const auto j2 = i, &k2 = i;
> ```

### 错误

答案显示`p is const int *.`，但是`p`应该是去掉了top-level const，所以`p`类型应该是`int *`，指向`const int`而已。

### 环境
- VS2012 Update 5

**Comment by pezy** [comment]
> 但是p应该是去掉了top-level const

理由呢？

**Comment by pezy** [comment]
> 所以说明它指向的是const int

所以它的类型是 const int * 有何问题？

**Comment by PoacherBro** [comment]
不好意思，是我弄错了，看到这个练习的时候我下意识把`p`的类型认为是`int *`。  
还是没有熟悉top-level const和low-level const在表达式里写法，把`const int *`认为成`int const *`。

**Comment by PoacherBro** [comment]
是的。
