### ISSUE TITLE
<Need a learn advice>是否有必要二刷C++Primer

### ISSUE THREAD

**Issue by KinoluKaslana** [pezy/CppPrimer#151]
Owner你好！
我是大概在半年前向您请教学习C++的注意事项的，现在我又来了，因为遇到了一个非常奇怪的现象：
在学习完C++primer之后，前前后后写了&模仿了一部分STL的实现eg:tuple和相应的gets，之后开始系统的学习CppReference的相关内容，其中也对C++的具名要求（named require）了解了一部分，但是其间并不太顺利——比如诸多语法细节eg:聚类的static initialization，拷贝构造等，都出现了遗忘，直到昨天突然翻起C++Primer，发现里面其实都多多少少的有介绍（虽然C++11就现在的C++14和C++17而言，略微显出了一点小问题，但是总体不变），就突然很觉得，是否有必要仔细的重新二刷C++Primer（PS：以及开始研究一些基础算法了，毕竟在本科阶段我个人主张还是以语言基础和算法为更本，自己的兴趣方向稍微代着一点）

**Comment by pezy** [comment]
> 开始系统的学习CppReference的相关内容

你都开始系统地学习 cpp reference 了，还有什么必要去看 C++ Primer 呢？这也就是一本入门书，显然，看你的描述，你已经是入门的了，为啥还来个二入，不理解。

既然是本科，不如多花点时间研究算法与其他语言吧，C++ 如果没有合适的项目依托，纯靠看书还是比较难以深入使用与体会的。
