### ISSUE TITLE
ex5_12.cpp中ff统计在某些情况下不准确。

### ISSUE THREAD

**Issue by 1608637229** [pezy/CppPrimer#152]
case 'i':
            if (prech == 'f') ++fiCnt;
这段后面缺少了break，导致fififi也会统计三次ff.

**Comment by pezy** [comment]
> 这段后面缺少了break，导致fififi也会统计三次ff.

毫无道理啊，这里加的是 `fiCnt`，跟 `ffCnt` 有啥关系？

**Comment by 1608637229** [comment]
另外直接prech = ch;这样会重复统计ff的数量吧例如输入fffff会算作5次ff。改成prech = (prech != 'f') ? ch : '0';判断下会不会更好，这样不会重复统计已经算过的f.

**Comment by 1608637229** [comment]
> > 这段后面缺少了break，导致fififi也会统计三次ff.
> 
> 毫无道理啊，这里加的是 `fiCnt`，跟 `ffCnt` 有啥关系？

没有break,不会跳出本次输入，直接执行下面的case'f',然后因为prech没有更新因此还是前一个f，就统计ff加1了。因此这个break肯定不能少

**Comment by pezy** [comment]
> 没有break,不会跳出本次输入，直接执行下面的case'f'

请问你执行过没有啊？在 case 'I' 那里就 break 了，怎么还可能到 case 'f' ?

**Comment by pezy** [comment]
> 例如输入fffff会算作5次ff

5次 ff 是怎么“算作”的？根据代码，这明显会输出 4 次好吗？请问你觉得应该是几次？

**Comment by 1608637229** [comment]
> > 例如输入fffff会算作5次ff
> 
> 5次 ff 是怎么“算作”的？根据代码，这明显会输出 4 次好吗？请问你觉得应该是几次？

我少打一个，ffffff会输出5次，我肯定执行了。不执行怎么验证。

**Comment by 1608637229** [comment]
> > 没有break,不会跳出本次输入，直接执行下面的case'f'
> 
> 请问你执行过没有啊？在 case 'I' 那里就 break 了，怎么还可能到 case 'f' ?

你那个地方没加break，我是复制过去运行的。不加break就出不去{}，prech =ch执行不到自然出问题。一直读入下一个ch。你自己运行fififi试试。

**Comment by pezy** [comment]
> 你自己运行fififi试试。

https://www.jdoodle.com/a/Fir

![image](https://user-images.githubusercontent.com/1147451/45665475-b04f7380-bb43-11e8-80ac-0e9efdcb550e.png)

**Comment by 1608637229** [comment]
> > 你自己运行fififi试试。
> 
> https://www.jdoodle.com/a/Fir
> 
> ![图片](https://user-images.githubusercontent.com/1147451/45665475-b04f7380-bb43-11e8-80ac-0e9efdcb550e.png)
抱歉我的问题，下面的大写的I里有break。因为我把这段删了只留了i,f,l才出现的问题。
