### ISSUE TITLE
ex9_51.cpp

### ISSUE THREAD

**Issue by 1608637229** [pezy/CppPrimer#153]
小问题啊，你上面的month 和 day搞反了。在case 0x10里，还有输出的时候。外国的日期是 月/日/年。
另外这句是不是应该大于等于5啊，if (s.find_first_of(",") >= 4 && s.find_first_of(",") != std::string::npos)
中间有个空格。

**Comment by pezy** [comment]
谢谢反馈，的确是反了。

这份代码貌似是 Mooophy 最早的代码遗留。。。看起来也比较费解。。。我打算直接重写了～
