### ISSUE TITLE
请问使用cin接收char类型，如何表示输入结束？

### ISSUE THREAD

**Issue by JisuiWang** [pezy/CppPrimer#155]
您好，请问像ex5_10.cpp中
`...
char ch;
while (std::cin >> ch)
...`
在运行时，输入什么来表示输入结束？

**Comment by pezy** [comment]
请自行搜一下，如何输入 EOF

**Comment by 1608637229** [comment]
windows系统是ctrl加z

**Comment by JisuiWang** [comment]
@1608637229 谢谢，我用的编辑器是CLion，好像需要设置一下才可以使用ctrl+z作为EOF，现在问题解决了。

**Comment by JisuiWang** [comment]
@pezy 谢谢。
