### ISSUE TITLE
ex16_29_blob.h operator--

### ISSUE THREAD

**Issue by DanielDFY** [pezy/CppPrimer#171]
### Exercise information

Exercise 16.29
> Revise your Blob class to use your version of shared_ptr rather than the library version.

### Question or Bug

```
// blob.h
template <typename T> inline BlobPtr<T>& BlobPtr<T>::operator--()
{
    --curr;
    check(-1, "decrement past begin of Blob<T>Ptr");
    return *this;
}

template <typename T> inline ConstBlobPtr<T>& ConstBlobPtr<T>::operator--()
{
    --curr;
    check(-1, "decrement past begin of ConstBlob<T>Ptr");
    return *this;
}

template <typename T> inline SharedPtr<vector<T>> BlobPtr<T>::check(size_t i, const T& msg) const
{
    auto ret = wptr.lock();
    if (!ret) throw std::runtime_error("unbound Blob<T>Ptr");
    if (i >= ret->size()) throw std::out_of_range(msg);
    return ret;
}
```

In the definitions of operator--, after line *--curr*, -1 is passed to function *check* as the size_t parameter *i*. Because of this, *i >= ret->size()* inside *check* will always be true and *check* will always throw an exception. Maybe you originally want to use *curr* as the argument here?

**Comment by pezy** [comment]
Yes, you are right. Could you please pull a request about this?
