### ISSUE TITLE
可否将答案做成一个pdf以便打印

### ISSUE THREAD

**Issue by thebestwayto** [pezy/CppPrimer#37]
这样看起来舒服一点啊、、

**Comment by pezy** [comment]
@thebestwayto 没做 PDF 有几个原因：

1. 目前的答案并不完整，仍需补全。
2. 本人精力有限，暂无充裕时间去做 PDF。

最后感谢你的建议，我会考虑将来去做这个。 :smile:

**Comment by jjjasperd** [comment]
@thebestwayto 喜欢可以自己做一个~毕竟大家都是码农 没太多业余时间。。。弄这个纯属个人爱好~
@pezy 您真是太有礼貌了 手动点赞！

**Comment by thebestwayto** [comment]
哇！感觉大家都好有爱啊！
@pezy 同楼上、点赞！！然后、、就还有个小问题啦、就是这个跟Mooophy的那个是什么关系啊？为什么不做成一个呢？

**Comment by pezy** [comment]
@thebestwayto 这个 repo 本来是 [Mooophy 那个](https://github.com/Mooophy/Cpp-Primer) 的 Fork, 后来独立出来有以下几个原因:

1. 非常荣幸, 后来 @Mooophy 让我做了那个 [repo](https://github.com/Mooophy/Cpp-Primer)  的管理员, 也就是说我可以直接对那个 repo 做修改了. 再通过我自己的 fork 去提交代码, 显得有点繁琐了.

2. @Mooophy 非常勤奋, 更新, 维护非常频繁, 那个 [repo](https://github.com/Mooophy/Cpp-Primer) 的 pull request 也更多, 发现的问题越多, 答案就越准确. 起初, 我还老耐着性子让我这个 fork 随时同步修改. 后来觉得好费劲, 也没太多意义. 不过让我删了这个 repo, 也觉得挺可惜, 最终就独立出来, 放一边不怎么管理了.

3. @Mooophy 比较前卫, 那个 [repo](https://github.com/Mooophy/Cpp-Primer) 已经开始计划升级到 C++ 14 标准了.  非常适合 C++ 爱好者尝鲜. 而我这个 repo 并无此打算, 希望和书本保持一致, 遵循 C++ 11 标准即可.

如果还有一些原因, 那就是对于一部分习题的解法, 我和 @Mooophy 的风格也存在一些初入. 保留自己的一份风格, 也算一点小私心了.

----

**综上, 我建议你去关注 @Mooophy 的那个 repo, 并帮助我们检查疏漏之处. 如果你有心, 更可以去补全那些遗漏的习题. 欢迎发 pull request 给那个 repo, 我和 @Mooophy 有空都会尽力去审查, 合并的.**

这个 repo, 完全可以取消关注, 我比较懒, 更新不会很频繁. 不过如果你有哪道题卡住了, 想多找几份答案对比参阅, 也可以在这里翻翻.

**Comment by Mooophy** [comment]
啊。。我也好懒。。

**Comment by thebestwayto** [comment]
原来如此、谢谢两位了！
