### ISSUE TITLE
exercise 2.31

### ISSUE THREAD

**Issue by DMLTZY** [pezy/CppPrimer#39]
第二章的练习2.31的第一个r1=v2应该是illegal的啊，这题不是用2.30里的声明么，2.30里v2是const int的，r1是int &的，所以是不行的啊

**Comment by pezy** [comment]
请区分一下**声明**与**赋值**.

`int& r1 = v2;` 肯定是不行的, 原因你说了. 但 `r1 = r2;` 中, `r1` 只不过是2.30 里 `v1` 的别名, 相当于是给 `v1` 赋予 `v2` 的值, 有何不可?

可用下述代码在编译器中验证:

```cpp
#include <iostream>

int main()
{
    const int v2 = 0; int v1 = v2;
    int &r1 = v1;
    r1 = v2;
}
```

**Comment by DMLTZY** [comment]
嗯，是我搞错了，r1她变了。你的回复里笔误写成“r1 = r2”了。我还有个问题是exercise2.35的那段代码的，不知道你代码里注释中的PKi是怎么在控制台显示出来的，我在vs2013里输入
cout << typeid(const int).name() << endl;     和
cout << typeid(int).name() << endl;  控制台都是int型，然后我查了一下（http://stackoverflow.com/questions/8888960/why-typeid-returns-that-int-and-const-int-are-same-types），说是typeid会忽略掉const，所以好像比不出来，看另一个人说用is_name就又查了下（http://www.cplusplus.com/reference/type_traits/is_same/），感觉用is_name更准点儿。朋友，我没鸡蛋里挑骨头的意思啊，以后还得向你多学   ：)

**Comment by pezy** [comment]
> 你的回复里笔误写成“r1 = r2”了。

的确笔误了，感谢纠正。

> 不知道你代码里注释中的PKi是怎么在控制台显示出来的

```cpp
typeid(p).name()
```

将输出 PKi, 手头没有 vs ，但在 gcc/clang 中验证。

> 感觉用is_name更准点儿

嗯， 学习了， 这个 `is_name` 的确更适合这道题， 方便的话， 可以提交一个 PR 来修改嘛？

> 朋友，我没鸡蛋里挑骨头的意思啊，以后还得向你多学 ：)

欢迎多挑骨头， 问题还很多， 互相学习～

**Comment by DMLTZY** [comment]
PR是什么啊？

**Comment by pezy** [comment]
> PR是什么啊？

[Pull request](https://help.github.com/articles/creating-a-pull-request/).
