### ISSUE TITLE
ex14_27_28_StrBlob.h  ptr递减运算符中的check参数问题

### ISSUE THREAD

**Issue by phoenixhanren** [pezy/CppPrimer#41]
209行和337行中 StrBlobPtr 和 ConstStrBlobPtr 的前缀递减运算符
check第一个参数是不是应该改成curr而不是-1...

**Comment by pezy** [comment]
@phoenixhanren 是的, 这里用 "-1" 毫无道理. 我查了一下, 原来当初写这个类的时候, 参考了书上的例子程序, 结果那个例子程序就写错了.... 真是坑爹.... :sob: 

谢谢~
