### ISSUE TITLE
A little neglect in Chapter 12/ex_12_27_30.cpp

### ISSUE THREAD

**Issue by wtlusvm** [pezy/CppPrimer#46]
When I try to compile ex_12_27_30_TEST.cpp, compiler complains that "back_inserter is not a member in std". And It turns out _iterator_ header hasn't been included in this cpp yet. It's a minor offense at most. But fix it anyway.

**Comment by pezy** [comment]
which compiler and version?

**Comment by wtlusvm** [comment]
Visual Studio 2015 with update 1
