### ISSUE TITLE
关于练习13_48

### ISSUE THREAD

**Issue by xyz4826757** [pezy/CppPrimer#47]
关于练习13_48其中的String s5 = baz()会触发拷贝构造函数吗？vs2008有触发，但Mingw5.3.0 没触发

**Comment by pezy** [comment]
从语义上讲，应该是触发 **移动构造函数**。但移动语义是在 C++ 11 之后引入的，所以在此之前，将表现为 **拷贝构造函数**。

vs2008 不支持 C++11，所以会触发拷贝构造。如果在 `String` 类定义中加上：

```cpp
String(String &&) noexcept;
String& operator=(String&&) noexcept;
```

那么在 VS2012, 2013, 2015 中，将触发移动构造。

以上是 Visual Studio 系编译器的行为，还是比较真实的还原了标准所规定的语义的。

-----

然而 Mingw 算是 GCC 在 Windows 上实现的简版，属于 GCC/Clang 系的编译器风格。

这类编译器对于这种情况，会默认进行优化，使得无论拷贝构造还是移动构造，都不会被触发。（因为它能够识别出来这是一个临时对象，用不着拷贝，连移动也可以省了。）

这种优化有一个专有名词，我们称之为"返回值优化 [RVO](https://en.wikipedia.org/wiki/Return_value_optimization)"。你可以点击链接查看更多细节。

**Comment by xyz4826757** [comment]
谢谢，感觉还有好多东西要学习

**Comment by wtlusvm** [comment]
@pezy 最新的VS2015.1默认也会进行“返回值优化”，根据维基百科的示例：
```
#include <iostream>
struct C {
	C() {}
	C(const C&) { std::cout << "A copy was made.\n"; }
};

C f() {
	return C();
}

int main() {
	std::cout << "Hello World!\n";
	C obj = f();
	return 0;
}
```
在VS2015.1内编译运行，只显示了Hello World!而没有A copy was made.
![image](https://cloud.githubusercontent.com/assets/11345624/13837425/2e9e2e7c-ec46-11e5-9775-9a2d2f4b4fe1.png)

**Comment by pezy** [comment]
@wtlusvm 谢谢提醒与补充。

VS2015.1 开始，开始[接纳 Clang 了](https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/)。

所以一些行为也越来越一致。

**Comment by wtlusvm** [comment]
原来如此！谢谢！
