### ISSUE TITLE
关于练习14_7

### ISSUE THREAD

**Issue by xyz4826757** [pezy/CppPrimer#48]
我copy下来编译后运行说不支持的16位应用程序，这是为何呢？另外为什么不用
`std::ostream& operator<<(std::ostream& os, const String& s)
{
    auto p = s.elements;
    while (p != s.end) os << *p++;
    return os;
}`
而是用这个来重载呢
`std::ostream& operator<<(std::ostream& os, const String& s)
{
    char* c = const_cast<char*>(s.c_str());
    while (*c != '\0') os << *c++;
    return os;
}`

**Comment by pezy** [comment]
> 我copy下来编译后运行说不支持的16位应用程序，这是为何呢？

这个应该是 编译器/IDE 的问题，我用 VS 2013 以及 GCC 4.9+, Clang 3.4+ 都没问题。


> 另外为什么不用
> `std::ostream& operator<<(std::ostream& os, const String& s) { auto p = s.elements; while (p != s.end) os << *p++; return os; }`
> 而是用这个来重载呢
> `std::ostream& operator<<(std::ostream& os, const String& s) { char* c = const_cast<char*>(s.c_str()); while (*c != '\0') os << *c++; return os; }`

先搞清楚这两个差别。最简单的办法就是用一个 vector<char> 来存储输出的每一个字符。

你会发现上面那种（书上的写法）存储的字符数量为 12. 而下面那种存储的字符数量为 11. 差在哪呢？细一看就知道，差在最后那个 `'\0'` 上了。上面的写法，输出的其实是：
```
H e l l o _ W o r l d \0
```
而下面的写法输出的是：
```
H e l l o _ W o r l d
```

在这道题里，我认为 `'\0'` 不属于我所定义 `String` 的一部分。`'\0'` 的存在只为了兼容 C 接口(`c_str()`)。所以我输出时，不会包含这一特殊字符。

**Comment by xyz4826757** [comment]
恩，的确如此，那为什么要用char* c = const_cast<char*>(s.c_str());而不是之间auto c = s.c_str()，让c为const char*呢，因为我觉得后面并未有改写字符的操作，为何要显示转化为char*呢？

**Comment by pezy** [comment]
额，有道理。回头有空改一下。
