### ISSUE TITLE
the answer of Exercise 2.32

### ISSUE THREAD

**Issue by tannx** [pezy/CppPrimer#50]
`Is the following code legal or not? If not, how might you make it legal?`
`int null = 0, *p = null;`

illegal.

` int null = 0, *p = nullptr; `
this answer could not passed by compiler.

` int null = 0, *p = &null; `
but this was worked. is it correct?

**Comment by samshaq19912009** [comment]
I think int null = 0, *p = &null; should work.

2016-03-28 12:09 GMT-07:00 tannx <notifications@github.com>:

**Comment by pezy** [comment]
> int null = 0, *p = nullptr;
> this answer could not passed by compiler.

which compiler? 
GCC5 and VS2013 can work. (check http://cpp.sh/5kme , No error.)

> int null = 0, *p = &null;
> but this was worked. is it correct?

sure. It is also a great answer.

**Comment by tannx** [comment]
@pezy 
this' my result.
![Uploading Screenshot from 2016-03-30 06-46-07.png…]()

**Comment by pezy** [comment]
@tannx 

This book talk about **C++ 11**, so you should add parameter like following:

```sh
g++ test_08.cpp -o test_08 -std=c++11
```

**Comment by tannx** [comment]
@pezy 
I see.
Thank you for your help.
