### ISSUE TITLE
我想请教一下关于cctype和cstddef的问题

### ISSUE THREAD

**Issue by tsyw** [pezy/CppPrimer#57]
使用这两个头文件里面定义的东西是不是不需要加using std::size_t; using std::toupper; 之类的声明？
我看了您的几个答案中没有写，我实际尝试的时候，无论加不加都不影响。

**Comment by tsyw** [comment]
我的想法是：是不是类名需要声明，而类里面的东西不需要加using

**Comment by pezy** [comment]
> 是不是类名需要声明，而类里面的东西不需要加using

不是，你碰到情况的另有原因。

> 使用这两个头文件里面定义的东西是不是不需要加using std::size_t; using std::toupper; 之类的声明？

`<cctype>` 和 `<cstddef>` 你观察到了没，两者都是以 `c` 开头的，他们原本都是 C语言的库。C++ 为了兼容 C，也将其封入了 STL。

所以当你加上 `std` 的时候，用的是 STL(c++) 中的函数；当你不加 `std` 的时候，用的是原生 C 语言的函数。目前绝大部分 C++ 编译器都可以编译 C 程序，所以让你产生了加不加都可以的错觉。

其实，在 C++ 11 之后，加上 `std` 是比较严谨，恰当的做法。如果我的部分答案没写，应该是疏忽了。回头有空我补上吧。。。

**Comment by tsyw** [comment]
谢谢，看来是我看书不仔细
