### ISSUE TITLE
noexcept编译错误

### ISSUE THREAD

**Issue by bumzy** [pezy/CppPrimer#58]
[CppPrimer/ch15/ex15.26/bulk_quote.h](https://github.com/pezy/CppPrimer/blob/master/ch15/ex15.26/bulk_quote.h)
[vczh的知乎回答](https://www.zhihu.com/question/48111949/answer/109170320?group_id=733036678112903168)

**Comment by pezy** [comment]
谢谢，master branch 的 15 章还有很多错误。你指出的这个，我在另一个分支中修复了， 还未及时合并到 master...

https://github.com/pezy/CppPrimer/blob/ch15/ch15/ex15_26_Bulk_quote.h

**Comment by pezy** [comment]
Fixed in https://github.com/pezy/CppPrimer/blob/master/ch15/ex15_26_Bulk_quote.h
