### ISSUE TITLE
Exercise 6.41

### ISSUE THREAD

**Issue by Roller44** [pezy/CppPrimer#62]
(c) 是不是非法的？只能省略尾部的实参，这里省略了 wd 的，却没省略 bckgrnd 的。

**Comment by pezy** [comment]
合法的，`init(14, '*');` 实际上是：`init(14, 42, ' ');` , 省略的是 `bckgrnd`, '*' 提升为 `int`， 作为 wd.

check: http://coliru.stacked-crooked.com/a/520f55dd0ee62aa1

![image](https://cloud.githubusercontent.com/assets/1147451/16920324/cf9e2426-4d3f-11e6-8cef-c0ff2e16546a.png)

**Comment by Roller44** [comment]
我一直不是很理解“提升”这个词的意思，请问书里有提到这方面内容吗？我只能找到只言片语。不知道什么对于什么是提升，什么对于什么不是提升。

**Comment by pezy** [comment]
> 我一直不是很理解“提升”这个词的意思

就是 Implicit Conversions

> 书里有提到这方面内容吗

当然有，4.11. Type Conversions 整个小结。

**Comment by Roller44** [comment]
4.11 当时也看不太懂，类型之间怎么比较大小呢？

**Comment by pezy** [comment]
不同类型之间的比较分为两步：
1. 类型的提升， 譬如 Integral Promotions，即，char 类型与 int 类型比较，char 类型会自动提升为 int。
2. 同类型之间的比较，都是 int 类型了，再比较大小。

> 
> The types `bool`, `char`, `signed char`, `unsigned char`, `short`, and `unsigned short` 
> are promoted to `int` if **all possible values of that type fit** in an `int`.
> Otherwise, the value is promoted to `unsigned int`.

关键就在于第一步，类型的提升，说白了，就是小类型往大类型看齐。bool，char 之类向 int 看齐；float 向 double 看齐。

**Comment by Roller44** [comment]
明白了，谢谢！
