### ISSUE TITLE
exercise 4.37 疑问

### ISSUE THREAD

**Issue by SlothSimon** [pezy/CppPrimer#67]
给出的答案如下：

    int i; double d; const string *ps; char *pc; void *pv;
    pv = (void*)ps; // pv = const_cast<string*>(ps); or pv = static_cast<void*>(const_cast<string*>(ps));
    i = int(*pc);   // i = static_cast<int>(*pc);
    pv = &d;        // pv = static_cast<void*>(&d);
    pc = (char*)pv; // pc = reinterpret_cast<char*>(pv);

但自己看书理解后做题，第二行考虑到*pc和i一个是char一个是int，和reinterpret_cast部分的例子差不多，感觉应该用reinterpret_cast。
而第四行考虑到是从pv的void*类型变到pc的char*类型，和static_cast给的第二个例子一样，感觉应该用static_cast。
不知道我理解上是否有误？

**Comment by pezy** [comment]
> 第二行考虑到pc和i一个是char一个是int，和reinterpret_cast部分的例子差不多，感觉应该用reinterpret_cast。

你说的例子是: 
```cpp
int *ip;
char *pc = reinterpret_cast<char*>(ip);
```
吗?

如果是, 那可完全不一样, 例子里, 是从 `int*` to `char*`, 这是地址层面的转换, 且使用不当, 会造成运行时错误.(书上针对这个例子, 就紧接着一个错误案例)

> ```cpp
> i = int(*pc);
> ```

第二行这个, 是 `char` to `int`, 就是基本类型转换而已. 甚至你不写这个 `int()` 也没事, 会自动提升. 所以应该使用 `static_cast`.

你看, 这完全不是一回事.

----

> 而第四行考虑到是从pv的void类型变到pc的char*类型，和static_cast给的第二个例子一样，感觉应该用static_cast。

先看你提到的第二个例子:

```cpp
void* p = &d; // ok: address of any nonconst object can be stored in a void*
// ok: converts void* back to the original pointer type
double *dp = static_cast<double*>(p);
```

注意下文提及的一句话:

> use a `static_cast `to cast the pointer back to its **original type**

所以可以推测, `d` 是个 double 类型的变量, 我们暂时将其地址转为 `void*`(可能为了适应调用接口, 可能为了网络传输), 然后通过 `static_cast` 再转为 `double*`, 从而正确取值.

也就是说, `static_cast` 在这里是一种 **还原**.

那么, 再回到咱们的问题, 第四行里, `pv` 是什么? 从命名看, 完全看不出其原来指向的是什么类型, `v` 似乎仅仅只是 `void` 的缩写. 那么我们将其转为 `char*`, 实际是一种冒风险的**强制转换**. 而并不是上面例子里的**还原**. 针对地址层面的强制转换, 用 `reinterpret_cast` 才是准确的.

**Comment by SlothSimon** [comment]
感结合说明又反复看了几遍例子，终于弄懂了！弄懂了后感觉问的问题好小白⋯⋯谢谢大神这么耐心的解释！
