### ISSUE TITLE
About ex7_26.h --definition of some functions

### ISSUE THREAD

**Issue by Sublele** [pezy/CppPrimer#74]
Some functions declared in ex7_26.h are definited in ex7_26.cpp. it's no problem as to exercise7.26.
But exercise 8.6 - 8.8 include the head file "ex7_26.h", without those definitions, exercise 8.6-8.8 can't run correctly.

**Comment by pezy** [comment]
> exercise 8.6-8.8 can't run correctly

Any error? Could you please post more information.

**Comment by Sublele** [comment]
When I run:
g++ ex8_06.cpp
*there will be a clang: error: *linker command failed with exit code 1 (use -v to see invocation)
More information is:
*Undefined symbols for architecture x86_64:*
"read(std::__1::basic_istream<char, std::__1::char_traits<char> >&, Sales_data&)", referenced from:
      _main in ex8_06-643a04.o
functions print and Sales_data::combine are the same.
I think the definition of read, print and combine should be in *ex7_26.h* instead of ex7_26.cpp.

**Comment by pezy** [comment]
> I think the definition of read, print and combine should be in ex7_26.h instead of ex7_26.cpp.

If we do like this way, putting all the codes in header. why we need ".cpp" files?
**The convention is that ".h" files are declarations, and ".cpp" files are definitions.**

And, you should compile the code as following:

```shell
g++ ex8_06.cpp ex7_26.cpp -std=c++11
```

Regards.

**Comment by Sublele** [comment]
get， Thanks
