### ISSUE TITLE
exercise 9.28

### ISSUE THREAD

**Issue by iials** [pezy/CppPrimer#76]
You should change the prev.

I think this function should be as below:

```cpp
void f(forward_list<string> &lst, string s1, string s2){
	auto prev = lst.before_begin();
	auto curr = lst.begin();
	bool flag = false;
	while(curr!=lst.end()){
		if (*curr == s1){
			flag = true;
			lst.insert_after(curr, s2);
			return;
		}
		prev = curr;
		curr++;
	}
	lst.insert_after(prev, s2);
}
```

**Comment by pezy** [comment]
Sorry, I cannot find any essential different with current version: https://github.com/pezy/CppPrimer/tree/master/ch09#exercise-928

Just change `for` loop to `while` loop... I don't see the point.

**Comment by iials** [comment]
You're right... I misread the for loop
