### ISSUE TITLE
ex5_19

### ISSUE THREAD

**Issue by ghost** [pezy/CppPrimer#79]
hello, maybe
error:  cout << (str1 <= str2 ? str1 : str2) << " is less than the other. "
right:  cout << (str1.size() <= str2.size() ? str1 : str2) << " is less than the other. "

**Comment by pezy** [comment]
Hi, @WuPeng2016 .

The question is **less than**, rather than **shorter than**. Thus, we should compare by alphabet order, not the length.

**Comment by Thor-repo** [comment]
Yes, Simple comparison with '<' operator on string should do.

> cout<<(s1<s2?s1:s2);
