### ISSUE TITLE
Exercise 2.21

### ISSUE THREAD

**Issue by likui911** [pezy/CppPrimer#96]
Exercise 2.21

Explain each of the following definitions. Indicate whether any are illegal and, if so, why.

int i = 0;
(b) int *ip = i;
这里（b）应该是合法的，i的值为0相当于空指针

**Comment by pezy** [comment]
> i的值为0相当于空指针

nullptr 有类型吗? i 是 int 型的, 这能 "相当于"? 不可想当然.

```
main.cpp:6:10: error: cannot initialize a variable of type 'int *' with an lvalue of type 'int'
    int *ip = i;
         ^    ~
```

check: http://coliru.stacked-crooked.com/a/0860103336850c2a

**Comment by likui911** [comment]
的确不可以想当然，谢谢
