### ISSUE TITLE
ex 3.34

### ISSUE THREAD

**Issue by Rodvi** [pezy/CppPrimer#97]
Why `p1 = &arr[0];` and `p2 = &arr[0].`? 
These pointers can point to different elements of the array (for example `p1 = &arr[1];`, `p2 = &arr[3];`).

**Comment by pezy** [comment]
> Why p1 = &arr[0]; and p2 = &arr[0].?

Because they point to the same array, rather than **the elements** of same array. But the statements make no sense. Sorry for the misleading.
