### ISSUE TITLE
Exercise7.27:ex7_27.h

### ISSUE THREAD

**Issue by SaeronMeng** [pezy/CppPrimer#98]
Pezy大神，首先很感谢您给像我这样的c++新手提供书上题目答案，非常感谢。
其次，我对于练习7.27中的Class中的display()方法有疑问，Screen类的width和height函数控制着contents的宽和高，而且类中有cursor成员，是不是暗示了"坐标"的概念？题目中的意思是不是打印contents的时候按坐标打印？如：
`Screen& Screen::display(ostream &os)`
`{`
`	for (int i = 0; i < height; ++i) {`
`		for (int j = 0; j < width; ++j) {`
`			os << contents[i*height + j];`
`		}`
`		os << endl;`
`	}`
`	return *this;`
`}`
这样会不会更合理一些？谢谢解答！

**Comment by pezy** [comment]
`do_display` 的实现在书中 7.3.2 节有给出, 也是简单的输出字符串. 

但你的想法也很有道理, 这不就是习题的意义么, 你想怎么实现都可以, 没有标准答案. 

不过, 

> `os << contents[i*height + j];`

你的这句可能有点问题, 你想输出的可能是: `contents[i * width + j]`.

不用客气. :smiley_cat:
